### ISSUE TITLE
"Try Again" message in quiz when 100% achieved

### ISSUE THREAD

**Issue by johnapaolino** [GA-WDI/fundamentals#133]
<img width="826" alt="screen shot 2016-05-20 at 11 04 18 am" src="https://cloud.githubusercontent.com/assets/6709615/15432084/b23f8198-1e7a-11e6-91a8-b2683c726c74.png">

**Comment by jeannyvaidya** [comment]
duplicate issue: https://github.com/GA-WDI/fundamentals/issues/132

**Comment by jeannyvaidya** [comment]
@johnapaolino thanks for logging this issue. I looked into Typeform and it doesn't have a way to make the message conditional on the number of questions that are answered correctly. I changed it to say "Redo Quiz" instead of "Try Again" for v3.0 (globally everyone is moving to v3.0 June 6). It's not a big difference, but a workaround for now. Let me know if you think there's something better message we can put.
