### ISSUE TITLE
Fundamentals Quizzes -- Not showing in Browser

### ISSUE THREAD

**Issue by bmartinowich** [GA-WDI/fundamentals#153]
![screen shot 2016-08-09 at 1 35 09 pm](https://cloud.githubusercontent.com/assets/12037713/17526658/30b2a1f4-5e36-11e6-81d5-350992a593bd.png)

**Comment by jnappy** [comment]
hey @bmartinowich i'm unable to replicate this error on my end with safari or chrome - i also asked a few other people to try...is this maybe an issue with your browser?

**Comment by jessicaGA** [comment]
This is a problem with caching in the browser. If you refresh the page it will fix the issue.

**Comment by mcalthrop** [comment]
I've been seeing the same thing all day today as I have been going through the Fundamentals material. Initially I just thought that there was no quiz for that particular chapter.

Suggest that we add text to the page to indicate to the student that they should refresh their browser if no quiz appears – otherwise we'll get students who turn up on the first day having not completed all the quizzes.

**Comment by jessicaGA** [comment]
Agreed. I'm adding this to the September 19th sprint.

**Comment by jnappy** [comment]
See https://github.com/GA-WDI/fundamentals/pull/162

**Comment by mcalthrop** [comment]
@jnappy: just wondering... has this been incorrectly closed?

From what I can see, the PR you referenced (#162) fixes a different issue (the Associative Array / Object description discussed in #154).
