### ISSUE TITLE
Students have issues w/ JSBin

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#182]
maybe instead  instead go over creating an index.html and script.js, linking the files, opening index.html in browser, and how to switch quickly and efficiently between these applications.

**Comment by jnappy** [comment]
thanks for flagging this @jshawl - can you elaborate or provide any kind of specific feedback?

**Comment by jshawl** [comment]
we don't use jsbin in class. students said verbally they would rather create an index.html and js file

**Comment by code-for-coffee** [comment]
We've been manually creating files as well; our only 'web based' resource for use in class is Codepen.

**Comment by drmikeh** [comment]
We use codepen and repl.it for small exercises and the local file system for anything medium to large in size / complexity.

**Comment by ZebGirouard** [comment]
Not sure if I should be piggy-backing or creating a new issue, but I've found this to be true, and unsure what exactly reproduces it.  Pretty sure it is navigating away and back to a JS Bin exercise:

Instructions say to "type your answers directly into the text editor below", but there is not a text editor. There is a link to JS Bin, and I suppose that is what is meant, but it is still not clear to me where the JS Bin editor went.

**Comment by ZebGirouard** [comment]
Continuing with yet another issue, when I click "Save" in JSBin, it takes me to a site with the JS Bin, it is blank, and it says "It looks like your last session crashed so I disabled Auto-Run JS for you"

This is an issue in exercise 4.4.1 because it very clearly tells students to save.  It seems like it auto-saves on change, so do we even need to tell students this?

**Comment by jshawl** [comment]
👍 🚢 'd
