### ISSUE TITLE
Do any markets use Sublime?

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#184]
I think most are using atom - http://fundamentals.generalassemb.ly/01_chapter/05_lesson.html

**Comment by jnappy** [comment]
looks like it's pretty even: 

![image](https://cloud.githubusercontent.com/assets/7819607/19085083/f119f902-8a36-11e6-8b5f-7ee88162e712.png)

going to close this issue

**Comment by jshawl** [comment]
More markets use atom - I recommend we follow the majority or add a second section in fundamentals

**Comment by jnappy** [comment]
There's a pretty good balance in those numbers, and for what students will be doing, Atom/Sublime are largely the same.   

Open to modifying this statement, if you want: 

"Check out the following video to learn how to download, install, and use Sublime Text 3! You'll need it (or another editor like it) in order to build your Memory Game assignment."

...maybe we can link out to Atom if they want to explore, but I'd prefer to keep it simple.

**Comment by jnappy** [comment]
@jshawl

**Comment by jnappy** [comment]
interesting: 

![image](https://cloud.githubusercontent.com/assets/7819607/19117770/31a09952-8ae8-11e6-8c1f-937d36af98fd.png)

again, still requires a large amount of work to reshoot or re-write a new chapter, but definitely something that should be prioritized for the next release

cc: @carmenejames , @amy (don't have her github)

**Comment by microsarah** [comment]
The ID team has decided to provide instructions for Sublime in Fundamentals. Instructors are welcome to present other code editors as options for their students.
