### ISSUE TITLE
JSBin Freezes and I lose all my work :(

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#211]
I produced this issue by copying the instructions below:

"h2 color to pale yellow: #fffebb. Set h2's border-bottom-color to #fffebb as well."

into the JSBin CSS tab.  If I then hit the `tab` key anywhere on this line, the whole page freezes.  If I try to refresh the page I get that Chrome "Kill or Wait" screen.  When I say "Kill", I lose all my work.

This seems like a tricky issue to debug, but we should definitely be aware of it.

**Comment by microsarah** [comment]
Thanks for flagging this. Based on what I've read, JSBin doesn't recommend one browser over another– otherwise we could add that note to the students. Unfortunately, because we're relying on this 3rd-party app, we'll run into bugs & crashes here and there.

The good news: the future Learning Platform (for all online content delivery) will host Fundamentals and we'll have more custom tools. Let's reopen this ticket or create a new one if we find specific, recurring issues with JSBin and need to switch.
