### ISSUE TITLE
parentNode() is not a function

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#297]
https://github.com/GA-WDI/fundamentals/blob/master/10_chapter/08_lesson.md#parentnode

**Comment by microsarah** [comment]
Also 
"THis will return the parent of the first `<li>` element, which, in this case, is the `<ul>` element since it wraps all the `<li` elements."

should be

*This will return the parent of the first `<li>` element, which, in this case, is the `<ul>` element since it wraps all the `<li>` elements.*

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/358
