### ISSUE TITLE
no mention of dot syntax

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#308]
https://github.com/GA-WDI/fundamentals/blob/master/11_chapter/08_lesson.md#objects-in-javascript

``` js
var myObj = {
  fundamentals: 'is good'
}

myObj.fundamentals //=> 'is good'
```

**Comment by ZebGirouard** [comment]
@jnappy , this is linked to a [quiz issue](https://github.com/GA-WDI/fundamentals/issues/342), and should be fixed in the CheatSheet as well.  Not sure if I should make a 3rd issue for that, but we would need to fix this in all three places:

1) The Unit 11 section on Objects
2) The Unit 11 Quiz
3) The Unit 11 CheatSheet
